TaskManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('my_task_manager.urls', namespace='my_task_manager')),
    url(r'^authorization/', include('authorization.urls',
                                     namespace='authorization')),
]

authorization/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.log_in, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.log_out, name='logout')
]

authorization/models.py
from django.db import models

# Create your models here.

authorization/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse


def log_in(request):
    if len(request.POST) == 0:
        return render(request, 'authorization/login.html')
    else:
        username = request.POST['login']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('my_task_manager:main'))
        else:
            return render(request, 'authorization/login.html', {
                'error_message': "Wrong username or password!"
            })


def register(request):
    if len(request.POST) == 0:
        return render(request, 'authorization/register.html')
    else:
        username = request.POST['login']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is None:
            User.objects.create_user(username=username, password=password)
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('my_task_manager:main'))
        else:
            return render(request, 'authorization/register.html', {
                'error_message': "User is already exist! Choose another login."
            })


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('my_task_manager:index'))

authorization/templates/authorization/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authorization/style.css' %}">
</head>
<body>
    <h3>Login</h3>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'authorization:login' %}" method="post">
        {% csrf_token %}
        login: <input type="text" name="login">
        password: <input type="password" name="password">
        <input type="submit" value="Login">
    </form>

    <p><a href="{% url 'authorization:register' %}">Register</a></p>
</body>
</html>

authorization/templates/authorization/register.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authorization/style.css' %}">
</head>
<body>
    <h3>Register</h3>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'authorization:register' %}" method="post">
        {% csrf_token %}
        login: <input type="text" name="login"><br>
        password: <input type="password" name="password"><br>
        <input type="submit" value="Register">
    </form>
</body>
</html>