TaskManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('my_task_manager.urls', namespace='my_task_manager')),
    url(r'^authorization/', include('authorization.urls',
                                     namespace='authorization')),
]

authorization/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.log_in, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.log_out, name='logout')
]

my_task_manager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/$', views.MainView.as_view(), name='main'),
    url(r'^tasks/(?P<pk>[0-9]+)/update/$', views.update_task_view,
        name='update_task_view'),
    url(r'^tasks/create_task/$', views.create_task, name='create_task'),
    url(r'^tasks/(?P<pk>[0-9]+)/update_task/$', views.update_task,
        name='update_task'),
    url(r'^tasks/(?P<pk>[0-9]+)/$', views.TaskDetailView.as_view(),
        name='task_detail'),
    url(r'^tasks/(?P<pk>[0-9]+)/completed/$', views.complete_task,
        name='task_complete'),
    url(r'^tasks/$', views.all_tasks_view, name='all_tasks'),
]

MyTaskManager/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    creator = models.ForeignKey(User, related_name='task_creator')
    responsible = models.ForeignKey(User, related_name='task_responsible')
    date_created = models.DateTimeField(default=timezone.now)
    date_completed = models.DateTimeField()
    completed = models.BooleanField(default=False)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.text

    def set_complete(self):
        self.completed = True
        self.date_completed = timezone.now

my_task_manager/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class ManagerTask(models.Manager):
    def create_task(self, responsible_name, text, creator_name,
                    date_created=timezone.now()):
        task = self.create(
                responsible=User.objects.get(username=responsible_name),
                text=text,
                creator=User.objects.get(username=creator_name),
                date_created=date_created
        )
        return task


class Task(models.Model):
    creator = models.ForeignKey(User, related_name='task_creator')
    responsible = models.ForeignKey(User, related_name='task_responsible')
    date_created = models.DateTimeField(default=timezone.now)
    date_completed = models.DateTimeField(null=True)
    completed = models.BooleanField(default=False)
    text = models.CharField(max_length=1000)

    objects = ManagerTask()

    def __str__(self):
        return self.text

    def set_complete(self):
        self.completed = True
        self.date_completed = timezone.now

my_task_manager/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
import datetime

from .models import Task


def index(request):
    """
    Site main page
    """
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('my_task_manager:main'))
    else:
        return HttpResponseRedirect(reverse('authorization:login'))


class MainView(generic.ListView):
    template_name = 'my_task_manager/main.html'
    context_object_name = 'user_tasks'

    def get_queryset(self):
        """
        Return all tasks for current user that are not completed.
        """
        return Task.objects.filter(
            responsible=self.request.user,
            completed=False,
        ).order_by('date_created')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MainView, self).dispatch(*args, **kwargs)


@login_required
def update_task_view(request, pk):
    task = get_object_or_404(Task, pk=pk)
    return render(request, 'my_task_manager/update_task.html', {
        'users_list': User.objects.all(),
        'task': task,
    })


@login_required
def update_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    responsible = request.POST['responsible']
    text = request.POST['text']

    task.creator = request.user
    task.responsible = User.objects.filter(username=responsible)[0]
    task.text = text
    task.save()

    return HttpResponseRedirect(reverse('my_task_manager:task_detail',
                                        args=(task.id,)))


@login_required
def create_task(request):
    if len(request.POST) == 0:
        return render(request, 'my_task_manager/create_task.html', context={
            'users_list': User.objects.all(),
        })
    else:
        responsible = request.POST['responsible']
        text = request.POST['text']
        task = Task.objects.create_task(
                creator_name=request.user.username,
                responsible_name=responsible,
                text=text
        )
        return HttpResponseRedirect(reverse('my_task_manager:task_detail',
                                            args=(task.id,)))


class TaskDetailView(generic.DetailView):
    model = Task
    template_name = 'my_task_manager/task_detail.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskDetailView, self).dispatch(*args, **kwargs)


@login_required
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.user != task.responsible:
        return render(request, 'my_task_manager/task_detail.html', {
            'error_message': "You can't complete another user task!",
        })
    else:
        task.date_completed = timezone.now()
        task.completed = True
        task.save()
        return HttpResponseRedirect(reverse('my_task_manager:main'))


@login_required
def all_tasks_view(request):
    if len(request.GET) != 0:
        # creator_name = request.GET['creator']
        creator = User.objects.filter(username=request.GET['creator'])
        # responsible_name = request.GET['responsible']
        responsible = User.objects.filter(username=request.GET['responsible'])
        is_created_from = request.GET.get('created_from', False)
        created_from = datetime.datetime(
                int(request.GET['created_from_year']),
                int(request.GET['created_from_month']),
                int(request.GET['created_from_day']),
                int(request.GET['created_from_hour']),
                int(request.GET['created_from_minute'])
        )
        is_created_to = request.GET.get('created_to', False)
        created_to = datetime.datetime(
                int(request.GET['created_to_year']),
                int(request.GET['created_to_month']),
                int(request.GET['created_to_day']),
                int(request.GET['created_to_hour']),
                int(request.GET['created_to_minute'])
        )
        is_finished_from = request.GET.get('finished_from', False)
        finished_from = datetime.datetime(
                int(request.GET['finished_from_year']),
                int(request.GET['finished_from_month']),
                int(request.GET['finished_from_day']),
                int(request.GET['finished_from_hour']),
                int(request.GET['finished_from_minute'])
        )
        is_finished_to = request.GET.get('finished_to', False)
        finished_to = datetime.datetime(
                int(request.GET['finished_to_year']),
                int(request.GET['finished_to_month']),
                int(request.GET['finished_to_day']),
                int(request.GET['finished_to_hour']),
                int(request.GET['finished_to_minute'])
        )
        finished = request.GET.get('finished', False)
        not_finished = request.GET.get('not_finished', False)

        tasks = Task.objects.all()
        if is_created_from == 'on':
            tasks = tasks.filter(date_created__gte=created_from)
        if is_created_to == 'on':
            tasks = tasks.filter(date_created__lte=created_to)
        if is_finished_from == 'on':
            tasks = tasks.filter(date_completed__gte=finished_from)
        if is_finished_to == 'on':
            tasks = tasks.filter(date_completed__lte=finished_to)
        if len(creator) != 0:
            tasks = tasks.filter(creator=creator[0])
        if len(responsible) != 0:
            tasks = tasks.filter(responsible=responsible[0])
        if finished is False:
            if not_finished == 'on':
                tasks = tasks.filter(completed=False)
        else:
            if not_finished is False:
                tasks = tasks.filter(completed=True)

        return render(request, 'my_task_manager/all_tasks.html', {
            'tasks_list': tasks.order_by('date_created'),
            'users_list': User.objects.all(),
        })
    else:
        return render(request, 'my_task_manager/all_tasks.html', {
            'tasks_list': Task.objects.order_by('date_created'),
            'users_list': User.objects.all(),
        })

my_task_manager/templates/my_task_manager/all_tasks.html
{% extends "my_task_manager/base_site.html" %}

{% block content %}
    <p>
    <form action="">
        <label>Responsible:
            <select required size="1" name="responsible">
                <option value="All" selected>All</option>
            {% for user_ in users_list %}
                <option value="{{ user_.get_username }}">{{ user_.get_username }}</option>
            {% endfor %}
            </select>
        </label>
        <label>Creator:
            <select required size="1" name="creator">
                <option value="All" selected>All</option>
            {% for user_ in users_list %}
                <option value="{{ user_.get_username }}">{{ user_.get_username }}</option>
            {% endfor %}
            </select>
        </label>
        <br>
        <label><input type="checkbox" name="created_from">Created from:
            day<input type="number" name="created_from_day" min="1" max="31" required value="1">
            month<input type="number" name="created_from_month" min="1" max="12" required value="1">
            year<input type="number" name="created_from_year" min="1970" max="2029" required value="1970">
            hour<input type="number" name="created_from_hour" min="0" max="23" required value="0">
            minute<input type="number" name="created_from_minute" min="0" max="59" required value="0">
        </label>
        <br>
        <label><input type="checkbox" name="created_to">Created to:
            day<input type="number" name="created_to_day" min="1" max="31" required value="31">
            month<input type="number" name="created_to_month" min="1" max="12" required value="12">
            year<input type="number" name="created_to_year" min="1970" max="2029" required value="2029">
            hour<input type="number" name="created_to_hour" min="0" max="23" required value="23">
            minute<input type="number" name="created_to_minute" min="0" max="59" required value="59">
        </label>
        <br>
        <label><input type="checkbox" name="finished_from">Finished from:
            day<input type="number" name="finished_from_day" min="1" max="31" required value="1">
            month<input type="number" name="finished_from_month" min="1" max="12" required value="1">
            year<input type="number" name="finished_from_year" min="1970" max="2029" required value="1970">
            hour<input type="number" name="finished_from_hour" min="0" max="23" required value="0">
            minute<input type="number" name="finished_from_minute" min="0" max="59" required value="0">
        </label>
        <br>
        <label><input type="checkbox" name="finished_to">Finished to:
            day<input type="number" name="finished_to_day" min="1" max="31" required value="31">
            month<input type="number" name="finished_to_month" min="1" max="12" required value="12">
            year<input type="number" name="finished_to_year" min="1970" max="2029" required value="2029">
            hour<input type="number" name="finished_to_hour" min="0" max="23" required value="23">
            minute<input type="number" name="finished_to_minute" min="0" max="59" required value="59">
        </label>
        <br>
        <label>Finished:
            <input type="checkbox" name="finished" checked>
        </label>
        <label>Not finished:
            <input type="checkbox" name="not_finished" checked>
        </label>
        <br>
        <input type="reset" value="Reset">
        <input type="submit" value="Filter">
    </form>
    </p>

    {% if tasks_list %}
        <table>
        <thead><tr>
            <td>Creator</td>
            <td>Responsible</td>
            <td>Task</td>
            <td>Created</td>
            <td>Completed</td>
            <td>Completion date</td>
        </tr></thead>
        <tbody>
        {% for task in tasks_list %}
            <tr>
            <td>{{ task.creator }}</td>
            <td>{{ task.responsible }}</td>
            <td><a href="{% url 'my_task_manager:task_detail' task.id %}">{{ task.text }}</a></td>
            <td>{{ task.date_created }}</td>
            <td>{{ task.completed }}</td>
            <td>{{ task.date_completed }}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% else %}
        <p>There are no tasks at all!</p>
    {% endif %}
{% endblock %}

my_task_manager/templates/my_task_manager/base_site.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Task Manager{% endblock %}</title>
    </head>
    <body>
        {% block header %}
            <section>
                <header>
                    <h4><form method="get">
                        Welcome, {{ user.get_username }}!
                        <button formaction="{% url 'authorization:logout' %}" type="submit">Logout</button>
                        <button formaction="{% url 'my_task_manager:main' %}" type="submit">Main</button>
                        <button formaction="{% url 'my_task_manager:all_tasks' %}" type="submit">All tasks</button>
                        <button formaction="{% url 'my_task_manager:create_task' %}" type="submit">Create task</button>
                    </form></h4>

                </header>
            </section>
        {% endblock %}
        {% block content %}{% endblock %}
    </body>
</html>

my_task_manager/templates/my_task_manager/create_task.html
{% extends "my_task_manager/base_site.html" %}

{% block content %}
<form action="{% url 'my_task_manager:create_task' %}" method="post">
    {% csrf_token %}
    Responsible:
    <select required size="1" name="responsible">
    {% for user_ in users_list %}
        <option value="{{ user_.get_username }}">{{ user_.get_username }}</option>
    {% endfor %}
    </select><br>
    Text:
    <textarea cols="80" rows="6" name="text" required maxlength="1000"></textarea>
    <input type="submit" value="Create"><br>
</form>
{% endblock %}

my_task_manager/templates/my_task_manager/main.html
{% extends "my_task_manager/base_site.html" %}

{% block content %}
{% if user_tasks %}
    <table>
    <thead><tr><td>Creator</td><td>Task</td><td>Created</td></tr></thead>
    <tbody>
    {% for task in user_tasks %}
        <tr>
        <td>{{ task.creator }}</td>
        <td><a href="{% url 'my_task_manager:task_detail' task.id %}">{{ task.text }}</a></td>
        <td>{{ task.date_created }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>You have no active tasks.</p>
{% endif %}
{% endblock %}

my_task_manager/templates/my_task_manager/task_detail.html
{% extends "my_task_manager/base_site.html" %}

{% block content %}
    Responsible: {{ task.responsible }}<br>
    Text: {{ task.text }}<br>
    Creator: {{ task.creator }}<br>
    Creation date: {{ task.date_created }}<br>
    Completed: {% if task.completed %}Yes{% else %}No{% endif %}<br>
    Complete date: {{ task.date_completed }}<br>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <p>
    <form method="post">
        {% csrf_token %}
        <button formaction="{% url 'my_task_manager:update_task_view' task.id %}" type="submit">Change task</button>
    </form>
    <form method="get">
        <button formaction="{% url 'my_task_manager:task_complete' task.id %}" type="submit" {% if user != task.responsible %}disabled{% endif %}>Completed</button>
    </form>
    </p>
{% endblock %}

my_task_manager/templates/my_task_manager/update_task.html
{% extends "my_task_manager/base_site.html" %}

{% block content %}
<form action="{% url 'my_task_manager:update_task' task.id %}" method="post">
    {% csrf_token %}
    Responsible:
    <select required size="1" name="responsible">
    {% for usr in users_list %}
        <option value="{{ usr.get_username }}" {% if task.responsible == usr.id %}selected{% endif %}>{{ usr.get_username }}</option>
    {% endfor %}
    </select><br>
    Text:
    <textarea cols="80" rows="6" name="text" required maxlength="1000">{{ task.text }}</textarea><br>
    <input type="submit" value="Update"><br>
    Creator: {{ task.creator }}<br>
    Creation date: {{ task.date_created }}<br>
    Completed: {% if task.completed %}Yes{% else %}No{% endif %}<br>
    Complete date: {{ task.date_completed }}<br>
</form>
{% endblock %}